Diagnostics:
  ClangTidy:
    Add:
      [
        performance-*,
        bugprone-*,
        portability-*,
        modernize-*,
        clang-analyzer-*,
        cppcoreguidelines-*,
        hicpp-*,
        misc-*,
        readability-*,
      ]
    Remove: [modernize-use-trailing-return-type, readability-redundant-access-specifiers, cppcoreguidelines-avoid-magic-numbers, readability-magic-numbers, cppcoreguidelines-pro-type-reinterpret-cast]

Completion:
  AllScopes: true

CompileFlags:
  Add: [-Wall, -Wextra, -Wno-c++98-compat, -Wno-c++98-compat-pedantic, -std=c++20]

Index:
  Background: Build
